### ISSUE TITLE
Config validation error when explicitly setting env.PORT

### ISSUE THREAD

**Issue by jlsan92** [strvcom/atlas.js#71]
I'm receiving a `ValidationError` when env var `PORT` is explicitly set. Probably because the variable is not cast to `Number` before (?)

https://github.com/strvcom/atlas.js/blob/998e1774a3335ec8be9c4c812a5959a32c4ad729/packages/koa/src/server.mjs#L40

Error received:

```js
[ { keyword: 'type',
    dataPath: '.listen.port',
    schemaPath: '#/properties/listen/properties/port/type',
    params: { type: 'number' },
    message: 'should be number' } ]
```

**Comment by robertrossmann** [comment]
Thanks, fixed in `@atlas.js/koa@3.2.0-alpha.9` 🎉
