### ISSUE TITLE
Yeoman generator does not finish

### ISSUE THREAD

**Issue by TobiasHennig** [strvcom/atlas.js#85]
Hi, i want to try out atlas.js and followed the instructions on https://www.npmjs.com/package/@atlas.js/generator-atlas. After running `yo @atlas.js/atlas` i answered all questions until it says "Is this OK? (Y/n)" (after it shows the package.json).

But no matter what I type ("y", "Y", ENTER), it doesn't go on. Do you know if it is an error with yeoman or with the generator?

My device: macOS Mojave, Terminal (zsh), node 10.15, yo 2.0.6

**Comment by robertrossmann** [comment]
Hi @TobiasHennig!

I just tried to bootstrap an Atlas.js app with the generator and it seems to be working fine... 🤷‍♂ Here are the steps I took:

```sh
npm i -g @atlas.js/generator-atlas@latest
# bunch of logs about installation progress...

yo @atlas.js/atlas
# Several prompts, then the final install
```

![yo prompts](https://user-images.githubusercontent.com/3058150/59900477-bb983e00-93f8-11e9-8d9e-ba7668909a75.png)

My guess would be that Yeoman has some trouble with `zsh` - could you try with `bash` or `sh` instead...?

**Comment by TobiasHennig** [comment]
Hi @robertrossmann, thanks for your help. I was not able to fix the problem (fresh install of node, reinstall generator, use bash instead of zsh), but i recognize problem some problems in yeoman too (unable to navigate or confirm dialogs), so it think i have a problem with yeoman, not with your generator.

**Comment by robertrossmann** [comment]
@TobiasHennig You should really try to test it with `bash` to make sure it's not your shell's fault... 🤔
